package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.AccesstokenScopes;
import com.huinfo.auth.as.model.AccesstokenScopesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccesstokenScopesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int countByExample(AccesstokenScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByExample(AccesstokenScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByPrimaryKey(Long accesstokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insert(AccesstokenScopes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insertSelective(AccesstokenScopes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    List<AccesstokenScopes> selectByExample(AccesstokenScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    AccesstokenScopes selectByPrimaryKey(Long accesstokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") AccesstokenScopes record, @Param("example") AccesstokenScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExample(@Param("record") AccesstokenScopes record, @Param("example") AccesstokenScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKeySelective(AccesstokenScopes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKey(AccesstokenScopes record);
}