package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.Client;
import com.huinfo.auth.as.model.ClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int countByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insertSelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    List<Client> selectByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    Client selectByPrimaryKey(Long id);
    
    /**
     * 根据ClientID查询对应的Client记录
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    Client selectByClientID(String clientID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") Client record, @Param("example") ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExample(@Param("record") Client record, @Param("example") ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKey(Client record);
}