package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.ResourceOwn;
import com.huinfo.auth.as.model.ResourceOwnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceOwnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int countByExample(ResourceOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int deleteByExample(ResourceOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int insert(ResourceOwn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int insertSelective(ResourceOwn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    List<ResourceOwn> selectByExample(ResourceOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    ResourceOwn selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") ResourceOwn record, @Param("example") ResourceOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByExample(@Param("record") ResourceOwn record, @Param("example") ResourceOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByPrimaryKeySelective(ResourceOwn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByPrimaryKey(ResourceOwn record);
}