
package com.huinfo.auth.as.model;

import java.util.Date;

public class Client {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.creationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Date creationdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.modificationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Date modificationdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientId
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String clientid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.contactEmail
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String contactemail;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.contactName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String contactname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.description
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.expireDuration
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Long expireduration;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String clientname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * client.notAllowedImplicitGrant
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Boolean notallowedimplicitgrant;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.secret
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String secret;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.skipConsent
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Boolean skipconsent;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.thumbNailUrl
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String thumbnailurl;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.useRefreshTokens
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Boolean userefreshtokens;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.resourceserver_id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Long resourceserverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.id
     *
     * @return the value of client.id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.id
     *
     * @param id the value for client.id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.creationDate
     *
     * @return the value of client.creationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.creationDate
     *
     * @param creationdate the value for client.creationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client.modificationDate
     *
     * @return the value of client.modificationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Date getModificationdate() {
        return modificationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.modificationDate
     *
     * @param modificationdate the value for client.modificationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setModificationdate(Date modificationdate) {
        this.modificationdate = modificationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientId
     *
     * @return the value of client.clientId
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientId
     *
     * @param clientid the value for client.clientId
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.contactEmail
     *
     * @return the value of client.contactEmail
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.contactEmail
     *
     * @param contactemail the value for client.contactEmail
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail == null ? null : contactemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.contactName
     *
     * @return the value of client.contactName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.contactName
     *
     * @param contactname the value for client.contactName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.description
     *
     * @return the value of client.description
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.description
     *
     * @param description the value for client.description
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client.expireDuration
     *
     * @return the value of client.expireDuration
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Long getExpireduration() {
        return expireduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.expireDuration
     *
     * @param expireduration the value for client.expireDuration
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setExpireduration(Long expireduration) {
        this.expireduration = expireduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientName
     *
     * @return the value of client.clientName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientName
     *
     * @param clientname the value for client.clientName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client.notAllowedImplicitGrant
     *
     * @return the value of client.notAllowedImplicitGrant
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Boolean getNotallowedimplicitgrant() {
        return notallowedimplicitgrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * client.notAllowedImplicitGrant
     *
     * @param notallowedimplicitgrant the value for
     *                                client.notAllowedImplicitGrant
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setNotallowedimplicitgrant(Boolean notallowedimplicitgrant) {
        this.notallowedimplicitgrant = notallowedimplicitgrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.secret
     *
     * @return the value of client.secret
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.secret
     *
     * @param secret the value for client.secret
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.skipConsent
     *
     * @return the value of client.skipConsent
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Boolean getSkipconsent() {
        return skipconsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.skipConsent
     *
     * @param skipconsent the value for client.skipConsent
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setSkipconsent(Boolean skipconsent) {
        this.skipconsent = skipconsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.thumbNailUrl
     *
     * @return the value of client.thumbNailUrl
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getThumbnailurl() {
        return thumbnailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.thumbNailUrl
     *
     * @param thumbnailurl the value for client.thumbNailUrl
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setThumbnailurl(String thumbnailurl) {
        this.thumbnailurl = thumbnailurl == null ? null : thumbnailurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client.useRefreshTokens
     *
     * @return the value of client.useRefreshTokens
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Boolean getUserefreshtokens() {
        return userefreshtokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.useRefreshTokens
     *
     * @param userefreshtokens the value for client.useRefreshTokens
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setUserefreshtokens(Boolean userefreshtokens) {
        this.userefreshtokens = userefreshtokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client.resourceserver_id
     *
     * @return the value of client.resourceserver_id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Long getResourceserverId() {
        return resourceserverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * client.resourceserver_id
     *
     * @param resourceserverId the value for client.resourceserver_id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setResourceserverId(Long resourceserverId) {
        this.resourceserverId = resourceserverId;
    }

    @Override
    public String toString() {
        return "Client{" + "id=" + id + ", creationdate=" + creationdate + ", modificationdate=" + modificationdate + ", clientid=" + clientid + ", contactemail=" + contactemail + ", contactname=" + contactname + ", description=" + description + ", expireduration=" + expireduration + ", clientname=" + clientname + ", notallowedimplicitgrant=" + notallowedimplicitgrant + ", secret=" + secret + ", skipconsent=" + skipconsent + ", thumbnailurl=" + thumbnailurl + ", userefreshtokens=" + userefreshtokens + ", resourceserverId=" + resourceserverId + '}';
    }
}