
package com.huinfo.auth.as.model;

public class ClientAttributes {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_attributes.client_id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Long clientId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * client_attributes.attribute_name
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String attributeName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * client_attributes.attribute_value
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String attributeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client_attributes.client_id
     *
     * @return the value of client_attributes.client_id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * client_attributes.client_id
     *
     * @param clientId the value for client_attributes.client_id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client_attributes.attribute_name
     *
     * @return the value of client_attributes.attribute_name
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * client_attributes.attribute_name
     *
     * @param attributeName the value for client_attributes.attribute_name
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName == null ? null : attributeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * client_attributes.attribute_value
     *
     * @return the value of client_attributes.attribute_value
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * client_attributes.attribute_value
     *
     * @param attributeValue the value for client_attributes.attribute_value
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }
}