package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.ClientRedirecturis;
import com.huinfo.auth.as.model.ClientRedirecturisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientRedirecturisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int countByExample(ClientRedirecturisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByExample(ClientRedirecturisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByPrimaryKey(Long clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insert(ClientRedirecturis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insertSelective(ClientRedirecturis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    List<ClientRedirecturis> selectByExample(ClientRedirecturisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    ClientRedirecturis selectByPrimaryKey(Long clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") ClientRedirecturis record, @Param("example") ClientRedirecturisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExample(@Param("record") ClientRedirecturis record, @Param("example") ClientRedirecturisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKeySelective(ClientRedirecturis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_redirecturis
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKey(ClientRedirecturis record);
}