
package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.ClientScopes;
import com.huinfo.auth.as.model.ClientScopesExample;
import java.util.List;
import java.util.Set;
import org.apache.ibatis.annotations.Param;

public interface ClientScopesMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int countByExample(ClientScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByExample(ClientScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insert(ClientScopes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insertSelective(ClientScopes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    List<ClientScopes> selectByExample(ClientScopesExample example);

    /**
     * 查询客户端对应的访问范围
     *
     * @param clientPrimaryKey
     * @return
     */
    List<String> selectByClientPrimaryKey(Long clientPrimaryKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") ClientScopes record, @Param("example") ClientScopesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_scopes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExample(@Param("record") ClientScopes record, @Param("example") ClientScopesExample example);
}
