package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.ClientAttributes;
import com.huinfo.auth.as.model.ClientAttributesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientAttributesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int countByExample(ClientAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByExample(ClientAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByPrimaryKey(Long clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insert(ClientAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insertSelective(ClientAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    List<ClientAttributes> selectByExample(ClientAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    ClientAttributes selectByPrimaryKey(Long clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") ClientAttributes record, @Param("example") ClientAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExample(@Param("record") ClientAttributes record, @Param("example") ClientAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKeySelective(ClientAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_attributes
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKey(ClientAttributes record);
}