package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.ResourceOwnInfo;
import com.huinfo.auth.as.model.ResourceOwnInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceOwnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int countByExample(ResourceOwnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int deleteByExample(ResourceOwnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int insert(ResourceOwnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int insertSelective(ResourceOwnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    List<ResourceOwnInfo> selectByExample(ResourceOwnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    ResourceOwnInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") ResourceOwnInfo record, @Param("example") ResourceOwnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByExample(@Param("record") ResourceOwnInfo record, @Param("example") ResourceOwnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByPrimaryKeySelective(ResourceOwnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_own_info
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    int updateByPrimaryKey(ResourceOwnInfo record);
}