package com.huinfo.auth.as.dao;

import com.huinfo.auth.as.model.ResourceServer;
import com.huinfo.auth.as.model.ResourceServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int countByExample(ResourceServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByExample(ResourceServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insert(ResourceServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int insertSelective(ResourceServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    List<ResourceServer> selectByExample(ResourceServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    ResourceServer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") ResourceServer record, @Param("example") ResourceServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByExample(@Param("record") ResourceServer record, @Param("example") ResourceServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKeySelective(ResourceServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceserver
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    int updateByPrimaryKey(ResourceServer record);
}