package com.huinfo.auth.as.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccessTokenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public AccessTokenExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationdateEqualTo(Date value) {
            addCriterion("creationDate =", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotEqualTo(Date value) {
            addCriterion("creationDate <>", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThan(Date value) {
            addCriterion("creationDate >", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("creationDate >=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThan(Date value) {
            addCriterion("creationDate <", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThanOrEqualTo(Date value) {
            addCriterion("creationDate <=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateIn(List<Date> values) {
            addCriterion("creationDate in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotIn(List<Date> values) {
            addCriterion("creationDate not in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateBetween(Date value1, Date value2) {
            addCriterion("creationDate between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotBetween(Date value1, Date value2) {
            addCriterion("creationDate not between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateIsNull() {
            addCriterion("modificationDate is null");
            return (Criteria) this;
        }

        public Criteria andModificationdateIsNotNull() {
            addCriterion("modificationDate is not null");
            return (Criteria) this;
        }

        public Criteria andModificationdateEqualTo(Date value) {
            addCriterion("modificationDate =", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateNotEqualTo(Date value) {
            addCriterion("modificationDate <>", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateGreaterThan(Date value) {
            addCriterion("modificationDate >", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("modificationDate >=", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateLessThan(Date value) {
            addCriterion("modificationDate <", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateLessThanOrEqualTo(Date value) {
            addCriterion("modificationDate <=", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateIn(List<Date> values) {
            addCriterion("modificationDate in", values, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateNotIn(List<Date> values) {
            addCriterion("modificationDate not in", values, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateBetween(Date value1, Date value2) {
            addCriterion("modificationDate between", value1, value2, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateNotBetween(Date value1, Date value2) {
            addCriterion("modificationDate not between", value1, value2, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalIsNull() {
            addCriterion("encodedPrincipal is null");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalIsNotNull() {
            addCriterion("encodedPrincipal is not null");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalEqualTo(String value) {
            addCriterion("encodedPrincipal =", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalNotEqualTo(String value) {
            addCriterion("encodedPrincipal <>", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalGreaterThan(String value) {
            addCriterion("encodedPrincipal >", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalGreaterThanOrEqualTo(String value) {
            addCriterion("encodedPrincipal >=", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalLessThan(String value) {
            addCriterion("encodedPrincipal <", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalLessThanOrEqualTo(String value) {
            addCriterion("encodedPrincipal <=", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalLike(String value) {
            addCriterion("encodedPrincipal like", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalNotLike(String value) {
            addCriterion("encodedPrincipal not like", value, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalIn(List<String> values) {
            addCriterion("encodedPrincipal in", values, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalNotIn(List<String> values) {
            addCriterion("encodedPrincipal not in", values, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalBetween(String value1, String value2) {
            addCriterion("encodedPrincipal between", value1, value2, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andEncodedprincipalNotBetween(String value1, String value2) {
            addCriterion("encodedPrincipal not between", value1, value2, "encodedprincipal");
            return (Criteria) this;
        }

        public Criteria andExpiresIsNull() {
            addCriterion("expires is null");
            return (Criteria) this;
        }

        public Criteria andExpiresIsNotNull() {
            addCriterion("expires is not null");
            return (Criteria) this;
        }

        public Criteria andExpiresEqualTo(Long value) {
            addCriterion("expires =", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresNotEqualTo(Long value) {
            addCriterion("expires <>", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresGreaterThan(Long value) {
            addCriterion("expires >", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresGreaterThanOrEqualTo(Long value) {
            addCriterion("expires >=", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresLessThan(Long value) {
            addCriterion("expires <", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresLessThanOrEqualTo(Long value) {
            addCriterion("expires <=", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresIn(List<Long> values) {
            addCriterion("expires in", values, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresNotIn(List<Long> values) {
            addCriterion("expires not in", values, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresBetween(Long value1, Long value2) {
            addCriterion("expires between", value1, value2, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresNotBetween(Long value1, Long value2) {
            addCriterion("expires not between", value1, value2, "expires");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenIsNull() {
            addCriterion("refreshToken is null");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenIsNotNull() {
            addCriterion("refreshToken is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenEqualTo(String value) {
            addCriterion("refreshToken =", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenNotEqualTo(String value) {
            addCriterion("refreshToken <>", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenGreaterThan(String value) {
            addCriterion("refreshToken >", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenGreaterThanOrEqualTo(String value) {
            addCriterion("refreshToken >=", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenLessThan(String value) {
            addCriterion("refreshToken <", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenLessThanOrEqualTo(String value) {
            addCriterion("refreshToken <=", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenLike(String value) {
            addCriterion("refreshToken like", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenNotLike(String value) {
            addCriterion("refreshToken not like", value, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenIn(List<String> values) {
            addCriterion("refreshToken in", values, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenNotIn(List<String> values) {
            addCriterion("refreshToken not in", values, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenBetween(String value1, String value2) {
            addCriterion("refreshToken between", value1, value2, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenNotBetween(String value1, String value2) {
            addCriterion("refreshToken not between", value1, value2, "refreshtoken");
            return (Criteria) this;
        }

        public Criteria andResourceowneridIsNull() {
            addCriterion("resourceOwnerId is null");
            return (Criteria) this;
        }

        public Criteria andResourceowneridIsNotNull() {
            addCriterion("resourceOwnerId is not null");
            return (Criteria) this;
        }

        public Criteria andResourceowneridEqualTo(String value) {
            addCriterion("resourceOwnerId =", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridNotEqualTo(String value) {
            addCriterion("resourceOwnerId <>", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridGreaterThan(String value) {
            addCriterion("resourceOwnerId >", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridGreaterThanOrEqualTo(String value) {
            addCriterion("resourceOwnerId >=", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridLessThan(String value) {
            addCriterion("resourceOwnerId <", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridLessThanOrEqualTo(String value) {
            addCriterion("resourceOwnerId <=", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridLike(String value) {
            addCriterion("resourceOwnerId like", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridNotLike(String value) {
            addCriterion("resourceOwnerId not like", value, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridIn(List<String> values) {
            addCriterion("resourceOwnerId in", values, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridNotIn(List<String> values) {
            addCriterion("resourceOwnerId not in", values, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridBetween(String value1, String value2) {
            addCriterion("resourceOwnerId between", value1, value2, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andResourceowneridNotBetween(String value1, String value2) {
            addCriterion("resourceOwnerId not between", value1, value2, "resourceownerid");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Long value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Long value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Long value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Long value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Long value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Long value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Long> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Long> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Long value1, Long value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Long value1, Long value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accesstoken
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 13 14:41:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accesstoken
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}