package com.huinfo.auth.as.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public ClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationdateEqualTo(Date value) {
            addCriterion("creationDate =", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotEqualTo(Date value) {
            addCriterion("creationDate <>", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThan(Date value) {
            addCriterion("creationDate >", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("creationDate >=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThan(Date value) {
            addCriterion("creationDate <", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThanOrEqualTo(Date value) {
            addCriterion("creationDate <=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateIn(List<Date> values) {
            addCriterion("creationDate in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotIn(List<Date> values) {
            addCriterion("creationDate not in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateBetween(Date value1, Date value2) {
            addCriterion("creationDate between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotBetween(Date value1, Date value2) {
            addCriterion("creationDate not between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateIsNull() {
            addCriterion("modificationDate is null");
            return (Criteria) this;
        }

        public Criteria andModificationdateIsNotNull() {
            addCriterion("modificationDate is not null");
            return (Criteria) this;
        }

        public Criteria andModificationdateEqualTo(Date value) {
            addCriterion("modificationDate =", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateNotEqualTo(Date value) {
            addCriterion("modificationDate <>", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateGreaterThan(Date value) {
            addCriterion("modificationDate >", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("modificationDate >=", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateLessThan(Date value) {
            addCriterion("modificationDate <", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateLessThanOrEqualTo(Date value) {
            addCriterion("modificationDate <=", value, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateIn(List<Date> values) {
            addCriterion("modificationDate in", values, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateNotIn(List<Date> values) {
            addCriterion("modificationDate not in", values, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateBetween(Date value1, Date value2) {
            addCriterion("modificationDate between", value1, value2, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andModificationdateNotBetween(Date value1, Date value2) {
            addCriterion("modificationDate not between", value1, value2, "modificationdate");
            return (Criteria) this;
        }

        public Criteria andClientidIsNull() {
            addCriterion("clientId is null");
            return (Criteria) this;
        }

        public Criteria andClientidIsNotNull() {
            addCriterion("clientId is not null");
            return (Criteria) this;
        }

        public Criteria andClientidEqualTo(String value) {
            addCriterion("clientId =", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotEqualTo(String value) {
            addCriterion("clientId <>", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThan(String value) {
            addCriterion("clientId >", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThanOrEqualTo(String value) {
            addCriterion("clientId >=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThan(String value) {
            addCriterion("clientId <", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThanOrEqualTo(String value) {
            addCriterion("clientId <=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLike(String value) {
            addCriterion("clientId like", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotLike(String value) {
            addCriterion("clientId not like", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidIn(List<String> values) {
            addCriterion("clientId in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotIn(List<String> values) {
            addCriterion("clientId not in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidBetween(String value1, String value2) {
            addCriterion("clientId between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotBetween(String value1, String value2) {
            addCriterion("clientId not between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andContactemailIsNull() {
            addCriterion("contactEmail is null");
            return (Criteria) this;
        }

        public Criteria andContactemailIsNotNull() {
            addCriterion("contactEmail is not null");
            return (Criteria) this;
        }

        public Criteria andContactemailEqualTo(String value) {
            addCriterion("contactEmail =", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotEqualTo(String value) {
            addCriterion("contactEmail <>", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailGreaterThan(String value) {
            addCriterion("contactEmail >", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailGreaterThanOrEqualTo(String value) {
            addCriterion("contactEmail >=", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailLessThan(String value) {
            addCriterion("contactEmail <", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailLessThanOrEqualTo(String value) {
            addCriterion("contactEmail <=", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailLike(String value) {
            addCriterion("contactEmail like", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotLike(String value) {
            addCriterion("contactEmail not like", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailIn(List<String> values) {
            addCriterion("contactEmail in", values, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotIn(List<String> values) {
            addCriterion("contactEmail not in", values, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailBetween(String value1, String value2) {
            addCriterion("contactEmail between", value1, value2, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotBetween(String value1, String value2) {
            addCriterion("contactEmail not between", value1, value2, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactnameIsNull() {
            addCriterion("contactName is null");
            return (Criteria) this;
        }

        public Criteria andContactnameIsNotNull() {
            addCriterion("contactName is not null");
            return (Criteria) this;
        }

        public Criteria andContactnameEqualTo(String value) {
            addCriterion("contactName =", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotEqualTo(String value) {
            addCriterion("contactName <>", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameGreaterThan(String value) {
            addCriterion("contactName >", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameGreaterThanOrEqualTo(String value) {
            addCriterion("contactName >=", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameLessThan(String value) {
            addCriterion("contactName <", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameLessThanOrEqualTo(String value) {
            addCriterion("contactName <=", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameLike(String value) {
            addCriterion("contactName like", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotLike(String value) {
            addCriterion("contactName not like", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameIn(List<String> values) {
            addCriterion("contactName in", values, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotIn(List<String> values) {
            addCriterion("contactName not in", values, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameBetween(String value1, String value2) {
            addCriterion("contactName between", value1, value2, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotBetween(String value1, String value2) {
            addCriterion("contactName not between", value1, value2, "contactname");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andExpiredurationIsNull() {
            addCriterion("expireDuration is null");
            return (Criteria) this;
        }

        public Criteria andExpiredurationIsNotNull() {
            addCriterion("expireDuration is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredurationEqualTo(Long value) {
            addCriterion("expireDuration =", value, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationNotEqualTo(Long value) {
            addCriterion("expireDuration <>", value, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationGreaterThan(Long value) {
            addCriterion("expireDuration >", value, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationGreaterThanOrEqualTo(Long value) {
            addCriterion("expireDuration >=", value, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationLessThan(Long value) {
            addCriterion("expireDuration <", value, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationLessThanOrEqualTo(Long value) {
            addCriterion("expireDuration <=", value, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationIn(List<Long> values) {
            addCriterion("expireDuration in", values, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationNotIn(List<Long> values) {
            addCriterion("expireDuration not in", values, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationBetween(Long value1, Long value2) {
            addCriterion("expireDuration between", value1, value2, "expireduration");
            return (Criteria) this;
        }

        public Criteria andExpiredurationNotBetween(Long value1, Long value2) {
            addCriterion("expireDuration not between", value1, value2, "expireduration");
            return (Criteria) this;
        }

        public Criteria andClientnameIsNull() {
            addCriterion("clientName is null");
            return (Criteria) this;
        }

        public Criteria andClientnameIsNotNull() {
            addCriterion("clientName is not null");
            return (Criteria) this;
        }

        public Criteria andClientnameEqualTo(String value) {
            addCriterion("clientName =", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotEqualTo(String value) {
            addCriterion("clientName <>", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameGreaterThan(String value) {
            addCriterion("clientName >", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameGreaterThanOrEqualTo(String value) {
            addCriterion("clientName >=", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLessThan(String value) {
            addCriterion("clientName <", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLessThanOrEqualTo(String value) {
            addCriterion("clientName <=", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLike(String value) {
            addCriterion("clientName like", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotLike(String value) {
            addCriterion("clientName not like", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameIn(List<String> values) {
            addCriterion("clientName in", values, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotIn(List<String> values) {
            addCriterion("clientName not in", values, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameBetween(String value1, String value2) {
            addCriterion("clientName between", value1, value2, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotBetween(String value1, String value2) {
            addCriterion("clientName not between", value1, value2, "clientname");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantIsNull() {
            addCriterion("notAllowedImplicitGrant is null");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantIsNotNull() {
            addCriterion("notAllowedImplicitGrant is not null");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantEqualTo(Boolean value) {
            addCriterion("notAllowedImplicitGrant =", value, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantNotEqualTo(Boolean value) {
            addCriterion("notAllowedImplicitGrant <>", value, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantGreaterThan(Boolean value) {
            addCriterion("notAllowedImplicitGrant >", value, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantGreaterThanOrEqualTo(Boolean value) {
            addCriterion("notAllowedImplicitGrant >=", value, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantLessThan(Boolean value) {
            addCriterion("notAllowedImplicitGrant <", value, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantLessThanOrEqualTo(Boolean value) {
            addCriterion("notAllowedImplicitGrant <=", value, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantIn(List<Boolean> values) {
            addCriterion("notAllowedImplicitGrant in", values, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantNotIn(List<Boolean> values) {
            addCriterion("notAllowedImplicitGrant not in", values, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantBetween(Boolean value1, Boolean value2) {
            addCriterion("notAllowedImplicitGrant between", value1, value2, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andNotallowedimplicitgrantNotBetween(Boolean value1, Boolean value2) {
            addCriterion("notAllowedImplicitGrant not between", value1, value2, "notallowedimplicitgrant");
            return (Criteria) this;
        }

        public Criteria andSecretIsNull() {
            addCriterion("secret is null");
            return (Criteria) this;
        }

        public Criteria andSecretIsNotNull() {
            addCriterion("secret is not null");
            return (Criteria) this;
        }

        public Criteria andSecretEqualTo(String value) {
            addCriterion("secret =", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotEqualTo(String value) {
            addCriterion("secret <>", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretGreaterThan(String value) {
            addCriterion("secret >", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretGreaterThanOrEqualTo(String value) {
            addCriterion("secret >=", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLessThan(String value) {
            addCriterion("secret <", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLessThanOrEqualTo(String value) {
            addCriterion("secret <=", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLike(String value) {
            addCriterion("secret like", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotLike(String value) {
            addCriterion("secret not like", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretIn(List<String> values) {
            addCriterion("secret in", values, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotIn(List<String> values) {
            addCriterion("secret not in", values, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretBetween(String value1, String value2) {
            addCriterion("secret between", value1, value2, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotBetween(String value1, String value2) {
            addCriterion("secret not between", value1, value2, "secret");
            return (Criteria) this;
        }

        public Criteria andSkipconsentIsNull() {
            addCriterion("skipConsent is null");
            return (Criteria) this;
        }

        public Criteria andSkipconsentIsNotNull() {
            addCriterion("skipConsent is not null");
            return (Criteria) this;
        }

        public Criteria andSkipconsentEqualTo(Boolean value) {
            addCriterion("skipConsent =", value, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentNotEqualTo(Boolean value) {
            addCriterion("skipConsent <>", value, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentGreaterThan(Boolean value) {
            addCriterion("skipConsent >", value, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("skipConsent >=", value, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentLessThan(Boolean value) {
            addCriterion("skipConsent <", value, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentLessThanOrEqualTo(Boolean value) {
            addCriterion("skipConsent <=", value, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentIn(List<Boolean> values) {
            addCriterion("skipConsent in", values, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentNotIn(List<Boolean> values) {
            addCriterion("skipConsent not in", values, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentBetween(Boolean value1, Boolean value2) {
            addCriterion("skipConsent between", value1, value2, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andSkipconsentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("skipConsent not between", value1, value2, "skipconsent");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlIsNull() {
            addCriterion("thumbNailUrl is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlIsNotNull() {
            addCriterion("thumbNailUrl is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlEqualTo(String value) {
            addCriterion("thumbNailUrl =", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlNotEqualTo(String value) {
            addCriterion("thumbNailUrl <>", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlGreaterThan(String value) {
            addCriterion("thumbNailUrl >", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlGreaterThanOrEqualTo(String value) {
            addCriterion("thumbNailUrl >=", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlLessThan(String value) {
            addCriterion("thumbNailUrl <", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlLessThanOrEqualTo(String value) {
            addCriterion("thumbNailUrl <=", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlLike(String value) {
            addCriterion("thumbNailUrl like", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlNotLike(String value) {
            addCriterion("thumbNailUrl not like", value, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlIn(List<String> values) {
            addCriterion("thumbNailUrl in", values, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlNotIn(List<String> values) {
            addCriterion("thumbNailUrl not in", values, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlBetween(String value1, String value2) {
            addCriterion("thumbNailUrl between", value1, value2, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andThumbnailurlNotBetween(String value1, String value2) {
            addCriterion("thumbNailUrl not between", value1, value2, "thumbnailurl");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensIsNull() {
            addCriterion("useRefreshTokens is null");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensIsNotNull() {
            addCriterion("useRefreshTokens is not null");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensEqualTo(Boolean value) {
            addCriterion("useRefreshTokens =", value, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensNotEqualTo(Boolean value) {
            addCriterion("useRefreshTokens <>", value, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensGreaterThan(Boolean value) {
            addCriterion("useRefreshTokens >", value, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensGreaterThanOrEqualTo(Boolean value) {
            addCriterion("useRefreshTokens >=", value, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensLessThan(Boolean value) {
            addCriterion("useRefreshTokens <", value, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensLessThanOrEqualTo(Boolean value) {
            addCriterion("useRefreshTokens <=", value, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensIn(List<Boolean> values) {
            addCriterion("useRefreshTokens in", values, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensNotIn(List<Boolean> values) {
            addCriterion("useRefreshTokens not in", values, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensBetween(Boolean value1, Boolean value2) {
            addCriterion("useRefreshTokens between", value1, value2, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andUserefreshtokensNotBetween(Boolean value1, Boolean value2) {
            addCriterion("useRefreshTokens not between", value1, value2, "userefreshtokens");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdIsNull() {
            addCriterion("resourceserver_id is null");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdIsNotNull() {
            addCriterion("resourceserver_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdEqualTo(Long value) {
            addCriterion("resourceserver_id =", value, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdNotEqualTo(Long value) {
            addCriterion("resourceserver_id <>", value, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdGreaterThan(Long value) {
            addCriterion("resourceserver_id >", value, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdGreaterThanOrEqualTo(Long value) {
            addCriterion("resourceserver_id >=", value, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdLessThan(Long value) {
            addCriterion("resourceserver_id <", value, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdLessThanOrEqualTo(Long value) {
            addCriterion("resourceserver_id <=", value, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdIn(List<Long> values) {
            addCriterion("resourceserver_id in", values, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdNotIn(List<Long> values) {
            addCriterion("resourceserver_id not in", values, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdBetween(Long value1, Long value2) {
            addCriterion("resourceserver_id between", value1, value2, "resourceserverId");
            return (Criteria) this;
        }

        public Criteria andResourceserverIdNotBetween(Long value1, Long value2) {
            addCriterion("resourceserver_id not between", value1, value2, "resourceserverId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 13 14:41:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}