package com.huinfo.auth.as.model;

public class ResourceOwnInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.id
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.userID
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.domain
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.userName
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.nickName
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.photo
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.age
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private Long age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.sex
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.signature
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_own_info.ext
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    private String ext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.id
     *
     * @return the value of resource_own_info.id
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.id
     *
     * @param id the value for resource_own_info.id
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.userID
     *
     * @return the value of resource_own_info.userID
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.userID
     *
     * @param userid the value for resource_own_info.userID
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.domain
     *
     * @return the value of resource_own_info.domain
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.domain
     *
     * @param domain the value for resource_own_info.domain
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.userName
     *
     * @return the value of resource_own_info.userName
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.userName
     *
     * @param username the value for resource_own_info.userName
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.nickName
     *
     * @return the value of resource_own_info.nickName
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.nickName
     *
     * @param nickname the value for resource_own_info.nickName
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.photo
     *
     * @return the value of resource_own_info.photo
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.photo
     *
     * @param photo the value for resource_own_info.photo
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.age
     *
     * @return the value of resource_own_info.age
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public Long getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.age
     *
     * @param age the value for resource_own_info.age
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.sex
     *
     * @return the value of resource_own_info.sex
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.sex
     *
     * @param sex the value for resource_own_info.sex
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.signature
     *
     * @return the value of resource_own_info.signature
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.signature
     *
     * @param signature the value for resource_own_info.signature
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_own_info.ext
     *
     * @return the value of resource_own_info.ext
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_own_info.ext
     *
     * @param ext the value for resource_own_info.ext
     *
     * @mbggenerated Sun Apr 14 14:05:06 CST 2013
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }
}