package com.huinfo.auth.as.model;

public class ResourceServerScpoes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver_scopes.RESOURCESERVER_ID
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Long resourceserverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver_scopes.element
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String element;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourceserver_scopes.RESOURCESERVER_ID
     *
     * @return the value of resourceserver_scopes.RESOURCESERVER_ID
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Long getResourceserverId() {
        return resourceserverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourceserver_scopes.RESOURCESERVER_ID
     *
     * @param resourceserverId the value for resourceserver_scopes.RESOURCESERVER_ID
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setResourceserverId(Long resourceserverId) {
        this.resourceserverId = resourceserverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourceserver_scopes.element
     *
     * @return the value of resourceserver_scopes.element
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getElement() {
        return element;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourceserver_scopes.element
     *
     * @param element the value for resourceserver_scopes.element
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setElement(String element) {
        this.element = element == null ? null : element.trim();
    }
}