
package com.huinfo.auth.as.model;

import java.util.Date;

public class ResourceServer {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.creationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Date creationdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * resourceserver.modificationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private Date modificationdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.contactEmail
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String contactemail;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.contactName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String contactname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.description
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * resourceserver.resourceServerKey
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String resourceserverkey;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * resourceserver.resourceServerName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String resourceservername;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.owner
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String owner;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.secret
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String secret;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourceserver.thumbNailUrl
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    private String thumbnailurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourceserver.id
     *
     * @return the value of resourceserver.id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourceserver.id
     *
     * @param id the value for resourceserver.id
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.creationDate
     *
     * @return the value of resourceserver.creationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.creationDate
     *
     * @param creationdate the value for resourceserver.creationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.modificationDate
     *
     * @return the value of resourceserver.modificationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public Date getModificationdate() {
        return modificationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.modificationDate
     *
     * @param modificationdate the value for resourceserver.modificationDate
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setModificationdate(Date modificationdate) {
        this.modificationdate = modificationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.contactEmail
     *
     * @return the value of resourceserver.contactEmail
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.contactEmail
     *
     * @param contactemail the value for resourceserver.contactEmail
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail == null ? null : contactemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.contactName
     *
     * @return the value of resourceserver.contactName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.contactName
     *
     * @param contactname the value for resourceserver.contactName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.description
     *
     * @return the value of resourceserver.description
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.description
     *
     * @param description the value for resourceserver.description
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.resourceServerKey
     *
     * @return the value of resourceserver.resourceServerKey
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getResourceserverkey() {
        return resourceserverkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.resourceServerKey
     *
     * @param resourceserverkey the value for resourceserver.resourceServerKey
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setResourceserverkey(String resourceserverkey) {
        this.resourceserverkey = resourceserverkey == null ? null : resourceserverkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.resourceServerName
     *
     * @return the value of resourceserver.resourceServerName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getResourceservername() {
        return resourceservername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.resourceServerName
     *
     * @param resourceservername the value for resourceserver.resourceServerName
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setResourceservername(String resourceservername) {
        this.resourceservername = resourceservername == null ? null : resourceservername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourceserver.owner
     *
     * @return the value of resourceserver.owner
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourceserver.owner
     *
     * @param owner the value for resourceserver.owner
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.secret
     *
     * @return the value of resourceserver.secret
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourceserver.secret
     *
     * @param secret the value for resourceserver.secret
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * resourceserver.thumbNailUrl
     *
     * @return the value of resourceserver.thumbNailUrl
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public String getThumbnailurl() {
        return thumbnailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * resourceserver.thumbNailUrl
     *
     * @param thumbnailurl the value for resourceserver.thumbNailUrl
     *
     * @mbggenerated Sat Apr 13 14:41:24 CST 2013
     */
    public void setThumbnailurl(String thumbnailurl) {
        this.thumbnailurl = thumbnailurl == null ? null : thumbnailurl.trim();
    }
}